development:
  clients:
    default:
      database: tutor_list_development
      hosts:
        - localhost:27017
      options:
  options:

production:
  clients:
    default:
      database: <%= ENV['DB_NAME'] %>
      hosts:
        - localhost:27017
      options:
        user: <%= ENV['DB_USER'] %>
        password: <%= ENV['DB_PASSWORD'] %>
        roles:
            - 'dbOwner'
        auth_source: admin

test:
  clients:
    default:
      database: tutor_list_test
      hosts:
        - localhost:27017
      options:
        read:
        max_pool_size: 1
